call E:\sdy_opengl_sdd_doc_2018\distrib\bin\sdyddword.exe E:\sdy_opengl_sdd_doc_2018\test\PrimaryFlightDisplay PrimaryFlightDisplay软件设计说明.docx template_sdd_chn_shaviation.docx template_obj_chn_shaviation.docx E:\sdy_opengl_sdd_xml_2018\test\PrimaryFlightDisplay\PFD_sdd_chn.xml
pause
