/* Generated by SCADE Display */

#ifndef __TARGET_CONFIGURATION_H__
#define __TARGET_CONFIGURATION_H__

#include "sglConstants.h"
#include "sgl_types.h"

#define MAX_POINTERS 1
#define MAX_KEYBOARDS 1

extern unsigned long target_screen_width;
extern unsigned long target_screen_height;
extern const double ratio_x;
extern const double ratio_y;
extern const unsigned char target_rotation_mode;
extern const long target_periodicity;
extern const char *specification_name;

#define MAX_TOUCH_POINTS 1
#define POINTER_ID 0

#endif

